name: Validate YAML

on:
  push:
    paths:
      - '**.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt-get install yamllint -y
      - name: Lint YAML files
        run: yamllint .
